[versions]
assertjCore = "3.23.1"
gson = "2.10.1"
gsonFire = "1.8.5"
jacksonDatabindNullable = "0.2.6"
javaxAnnotationApi = "1.3.2"
jaxrs = "2.1.1"
junit4 = "4.13.2"
junitJupiter = "5.10.3"
lombok = "1.18.24"
mockitoCore = "5.1.1"
modelmapper = "2.4.4"
okHttp3 = "4.9.3"
okio = "2.10.0"
openApiGenerator = "6.2.0"
openapiGeneratorCli = "7.7.0"
#piTest = "1.7.4"
restassured = "5.4.0"
springBoot = "3.3.1"
springDependencyManagement = "1.1.6"
springDoc = "2.6.0"
swaggerAnnotations = "2.2.22"
validationApi = "2.0.1.Final"


[libraries]
# define modules as dependencies so they can be bundled
applicationModule = {module = 'nl.multicode.elevenproof:application', version = '1.0-SNAPSHOT'}
coreModule = {module = 'nl.multicode.elevenproof:core', version = '1.0-SNAPSHOT'}
generatedModule = {module = 'nl.multicode.elevenproof:generated', version = '1.0-SNAPSHOT'}
servicesModule = {module = 'nl.multicode.elevenproof:services', version = '1.0-SNAPSHOT'}

# other external dependencies
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
gsonFire = { group = "io.gsonfire", name = "gson-fire", version.ref = "gsonFire" }
jacksonDatabindNullable = { group = "org.openapitools", name = "jackson-databind-nullable", version.ref = "jacksonDatabindNullable" }
javaxAnnotationApi = { group = "javax.annotation", name = "javax.annotation-api", version.ref = "javaxAnnotationApi" }
jaxrs = { group = "javax.ws.rs", name = "javax.ws.rs-api", version.ref = "jaxrs" }
# test libs
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
junitJupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter" }
assertjCore = { group = "org.assertj", name = "assertj-core", version.ref = "assertjCore" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockitoJunitJupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockitoCore" }
restassured = { group = "io.rest-assured", name = "spring-mock-mvc", version.ref = "restassured" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
modelmapper = { group = "org.modelmapper", name = "modelmapper", version.ref = "modelmapper" }
okHttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp3" }
okHttp3LoggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp3" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
openapiGeneratorCli = { group = "org.openapitools", name = "openapi-generator-cli", version.ref = "openapiGeneratorCli" }
springdocOpenAPIGenerator = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springDoc" }
swaggerAnnotations = { group = "io.swagger.core.v3", name = "swagger-annotations", version.ref = "swaggerAnnotations" }
validationApi = { group = "javax.validation", name = "validation-api", version.ref = "validationApi" }

# version automatically set by spring-boot dependency management
springBootActuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
springBootTest = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
springBootValidation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
springBootWeb = { group = "org.springframework.boot", name = "spring-boot-starter-web" }

[bundles]
testBundle = ["junit4", "junitJupiterEngine", "junitJupiterParams", "assertjCore", "mockitoCore", "mockitoJunitJupiter"]

[plugins]
openApiGenerator = { id = "org.openapi.generator", version.ref = "openApiGenerator" }
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springBootDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
#piTest = { id = "info.solidsoft.pitest", version.ref = "piTest" }
